runtime: go111

service: caneconomy-data-api

env_variables:
  FIREBASE_KEY_PATH: "./firebase.json"
  ETH_NODE_URL: "https://inherently-fast-salmon.quiknode.io/568eb2c7-8118-47e6-a518-7549987fef57/z8XJtqvC36I59F-6Zt5egg==/"
  CANWORK_ESCROW_HASH: "0x6890f982416a44589cb044d2b136d8dce44483df"
  GIN_MODE: release

handlers:
- url: /.*
  script: auto